### PR TITLE
[perfrepo 2.0] Test executions 

### PR DESCRIPTION
**Pull request by grunwjir**
Test execution detail page was created - it's possible to create/edit/delete test execution (measured values of metrics, parameters). Test execution search was improved (advanced searching and mass operations are not implemented). File attachments are not working.

The view of metrics and alerts was changed. The list view was replaced by the table.

### CODE REVIEW

**Comment by Holmistr** [comment]
@grunwjir I cannot compile it. When running mvn clean install -DskipTests in the root directory, I get:
[INFO] bower ECONFLICT Unable to find suitable version for angular

**Comment by Holmistr** [comment]
@grunwjir https://gist.github.com/Holmistr/ca4ef40a515d9caab11d706d4aa6d546

**Comment by grunwjir** [comment]
@Holmistr I cloned the project and I don't have a problem. But I added bower resolution for AngularJS, please try it.

**Comment by Holmistr** [comment]
@grunwjir build still not passing, error: https://gist.github.com/Holmistr/c5f68053053e74404a1dc4d006947239

**Comment by Holmistr** [comment]
Closing as this is intercorporated into https://github.com/PerfCake/PerfRepo/pull/75

**Pull request closed without merging**
