### PR TITLE
PERFREPO-220 Update RF version

### PR DESCRIPTION
**Pull request by manovotn**
I managed to put together the bits I had and figure out few more things.

The branch is now rebased on top of master. Also I separated my work into three commits, each modifying certain type of files (pom changes, xhtml update and model updates due to changes in RF charts).
I also removed the formatting hell my IDE did there before.

I tested this manually on localhost (good old 'click-through') and that way found and fixed majority of problems with the xhtml pages. Although I am certain there will be some hidden areas I haven't bumped into.

One problem I know about is boxplot where it doesnt render the chart. For me (on localhost) it doesn't even work on current master so I guess its some misconfiguration on my side.
The error is: `TypeError: this.data.y.data[0] is undefined`
It would be nice if you could take a glance at it.

### CODE REVIEW

**Comment by manovotn** [comment]
Btw this should for now be considered a work in progress (you guys should have a label for that). I am off for today, but I will continue tommorow. See if I can find&fix something more :)

**Comment by manovotn** [comment]
Found and fixed few more minor issues:
- pop-ups in create/edit metric weren't resizing correctly upon opening and switching tabs
- hotkey for pop-up closing was not reacting
- could not switch to "All groups" in test search
- using reset in test execution search wasn't re-rendering the form (hence showing old values)

Other than that I haven't bumped into another issue(s). But that's far from claiming there are none.
@Holmistr at this point I will leave the PR to you for revision.

**Comment by Holmistr** [comment]
@manovotn Awesome, thank you very much! I will try to carefully review it in next few days and will let you know :)

**Comment by Holmistr** [comment]
I forgot to close this PR, since all of it's improvements are included in https://github.com/PerfCake/PerfRepo/pull/44 . Once again, thanks a lot, @manovotn !

**Pull request closed without merging**
